### ISSUE TITLE
The cloudslang guide for Atom installation and configuration should change

### ISSUE THREAD

**Issue by roieyal** [CloudSlang/atom-cloudslang-package#39] opened 2015-12-03 12:58 UTC
• Add prerequisites 
• Proxy configuration must come before package installation…
• Proxy configuration needs to be specified – it doesn’t work in windows
• After the CS package installation, 
![atom3](https://cloud.githubusercontent.com/assets/10178900/11561179/3e2aed00-99ce-11e5-9953-6b17c1fbba29.jpg)
Atom MUST be restarted or at least reloaded.
• Files with the .sl extension will be recognized as CS file in atom only and not in the windows file explorer…

**Comment by SamMarkowitz** [comment] 2015-12-14 12:41
Partially duplicate of #35 and #38.

**Closed as completed** 2015-12-14 13:52 UTC
Labels: enhancement
